### ISSUE TITLE
Nessuna categoria selezionata nello step2

### ISSUE THREAD

**Issue by 94tinat** [ProgettoLAM/FourEvent.user.droid#1]
Gestione nello step2 e step3 (dove sono presenti i TODO)

**Comment by gspinaci** [comment]
L'errore viene triggerato quando si tenta di aggiungere una lista di categorie, all'utente che non è stato inizializzato.

Necessario rendere obbligatoria la creazione dell'utente, nel primo step.

Rendo obbligatoria l'inserimento del nome/cognome

**Comment by gspinaci** [comment]
Sto valutando come bloccare un li bottone next 
https://github.com/fcannizzaro/material-stepper
