### ISSUE TITLE
Visualizzazione preferiti all'apertura dell'Activity

### ISSUE THREAD

**Issue by 94tinat** [ProgettoLAM/FourEvent.user.droid#2]
Errore di riempimento della stella dei preferiti all'apertura dell'Activity, presente in ogni evento salvato nei preferiti.

---

**Edit:**

Quando viene salvato almeno un evento nei preferiti, all'apertura dell'activity (dopo che è stata chiusa l'app) per ogni evento, la stella è colorata, nel fragment **AllEventsFragment**

**Comment by gspinaci** [comment]
Inizio la risoluzione dell'issue
